### ISSUE TITLE
CI ignores RES buildout constraints

### ISSUE THREAD

**Issue by oruhnau** [lisazeyen/hydrogen_policy#7]
I noticed that CI ignores buildout constraints, as can be seen here for the example of BE under annual matching (res1p2). We should fix this at some point.

![grafik](https://github.com/lisazeyen/hydrogen_policy/assets/40352101/a9a427bc-cb0a-4a0c-a01e-5763e32f5582)

**Comment by lisazeyen** [comment]
should be added something similar as [here](https://github.com/PyPSA/pypsa-eur/blob/b1d999f35d7492f3626ff09a1f27446a0484444f/scripts/solve_network.py#L52-L112)
